# Generated by Django 2.2 on 2020-03-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('wish_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='likes',
        ),
        migrations.AddField(
            model_name='wish',
            name='likes',
            field=models.ManyToManyField(related_name='wish_likes', to='login_app.User'),
        ),
    ]
